// app/og/house-card/route.tsx

import { ImageResponse } from "next/og";
import { getUserByFid } from "@/lib/neynar";
import {
  getHouseByFid,
  getOrCreateHouseForUser
} from "@/lib/storage";
import { generateHouseForUser } from "@/lib/house-generator";

export const runtime = "edge";

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const fid = Number(searchParams.get("fid") || "0");

  if (!fid) {
    return new Response("Missing fid", { status: 400 });
  }

  const user = await getUserByFid(fid);
  if (!user) {
    return new Response("User not found", { status: 404 });
  }

  let stored = await getHouseByFid(fid);
  if (!stored) {
    stored = await getOrCreateHouseForUser({
      fid,
      username: user.username,
      followers: user.follower_count,
      following: user.following_count
    });
  }

  const result =
    stored ??
    generateHouseForUser({
      username: user.username,
      followers: user.follower_count,
      following: user.following_count
    });

  return new ImageResponse(
    (
      <div
        style={{
          height: "100%",
          width: "100%",
          display: "flex",
          flexDirection: "column",
          background: "linear-gradient(135deg, #0f172a, #1e293b)",
          color: "white",
          padding: "40px",
          fontSize: 32,
          fontFamily: "system-ui, sans-serif"
        }}
      >
        <div style={{ fontSize: 32, opacity: 0.8 }}>
          RealEstate Rizz – Onchain House
        </div>
        <div style={{ marginTop: 24, fontSize: 40, fontWeight: 700 }}>
          @{result.username}
        </div>
        <div style={{ marginTop: 16, fontSize: 28 }}>
          🏡 {result.houseType}
        </div>
        <div style={{ marginTop: 16, fontSize: 24 }}>
          📍 {result.addressLine}
        </div>
        <div style={{ marginTop: 16, fontSize: 24 }}>
          💸 {result.absurdPrice}
        </div>
        <div style={{ marginTop: 16, fontSize: 22 }}>
          📊 {result.investmentScore}/10 – {result.investmentNote}
        </div>
        <div style={{ marginTop: 8, fontSize: 20 }}>
          ✨ {result.vibeLabel}
        </div>
        <div style={{ marginTop: 8, fontSize: 20 }}>
          ⚠️ {result.riskLabel}
        </div>
        <div
          style={{
            marginTop: "auto",
            fontSize: 20,
            opacity: 0.7
          }}
        >
          Generated by RealEstate Rizz 🏡
        </div>
      </div>
    ),
    {
      width: 1200,
      height: 630
    }
  );
}
